[package]
name = "wavebender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
basic_waves = "0.1.1"
eframe = "0.21.3"
egui = "0.21.0"
rand = "0.8.5"
rodio = "0.17.1"
tracing-subscriber = "0.3.16"
